[env:esp32s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200

build_flags =
  -DLV_CONF_INCLUDE_SIMPLE
  -DUSE_LVGL=1
  -DDISPLAY_UPDATE_INTERVAL_SEC=1
  -DSCANNER_CONTROL_USE_TRIGGER
  -DSCANNER_CONTROL_USE_SERIAL
  -DLV_FONT_MONTSERRAT_14=1
  -DLV_FONT_MONTSERRAT_28=1
  -DLV_FONT_MONTSERRAT_48=1
lib_deps =
  lvgl/lvgl@8.3.11
  zinggjm/GxEPD2@^1.6.2
  adafruit/Adafruit GFX Library@^1.11.10
  adafruit/Adafruit NeoPixel@^1.12.3

[env:esp32s2_mini_gdey1085f51]
extends = esp32s2_mini
build_flags =
  -DUSE_EPD_GDEY1085F51
